=== Iamgovinda/BCA3rdSem/Webtechnology/XML/ab.dtd
<!ELEMENT addressbook (title,(contact)+)> 
<!ELEMENT title (#PCDATA)>
<!ELEMENT contact (name, address, city, phone, email, company)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)> 
<!ELEMENT phone (mobile, home_no?)>
<!ELEMENT mobile (#PCDATA)> 
<!ELEMENT home_no (#PCDATA)> 
<!ELEMENT email (#PCDATA)> 
<!ELEMENT company (#PCDATA)>
<!ELEMENT g (#PCDATA)>

=== Iamgovinda/BCA3rdSem/Webtechnology/XML/xml2.xml
<?xml version= "1.0"?>
<!DOCTYPE addressbook SYSTEM "ab.dtd">
<addressbook>
    <title>My Address Book</title>
    <contact> 
        <name>Rabi Shrestha</name> 
        <address>Swoyambhu</address> 
        <city>Kathmandu</city> 
        <phone>
            <mobile>9851258639</mobile>
            <home_no>0123456</home_no> 
        </phone>
        <email>rabishrestha@gmail.com</email>
        <company>My Company</company>
    </contact>

    <contact> 
        <name>Rabi Shrestha</name> 
        <address>Swoyambhu</address> 
        <city>Kathmandu</city> 
        <phone>
            <mobile>9851258639</mobile>
            <home_no>0123456</home_no> 
        </phone>
        <email>rabishrestha@gmail.com</email>
        <company>My Company</company>
    </contact>
    
</addressbook>
