=== Iamgovinda/BCA3rdSem/Webtechnology/XML/Question6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name = "students">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="student" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType> 
    </xs:element>
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="address" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                    <xs:enumeration value="permanent"/>
                                    <xs:enumeration value="temporary"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="phone">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:pattern value="\d{10}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="website" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Iamgovinda/BCA3rdSem/Webtechnology/XML/Question6.xml
<?xml version = "1.0"?> 
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Question6.xsd">
    <student>
        <name>AKRITI SUBEDI</name>
        <address>KTM</address>
        <phone>0123456789</phone>
        <website>www.website.com</website>
    </student>
    <student>
        <name>ANISHA  RAI</name>
        <address type="permanent">BKT</address>
        <address type="temporary">abc</address>
        <phone >0123456789</phone>
        <website>www.website.com</website>
    </student>
    <student>
        <name>ANUP SHRESTHA</name>
        <address>LPT</address>
        <phone>0123456780</phone>
        <website>www.website.com</website>
    </student>
    <student>
        <name>BISHAL KC</name>
        <address>DRN</address>
        <phone>0123456789</phone>
        <website>www.website.com</website>
    </student>
</students>
