=== Iamgovinda/BCA3rdSem/Webtechnology/XML/sarika.dtd
<!ELEMENT shop (food+)>
<!ELEMENT food (name,type,cost?,boge?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT boge (#PCDATA)>

<!ATTLIST shop location CDATA #REQUIRED>
<!ATTLIST shop size CDATA #REQUIRED>
<!ATTLIST shop name CDATA #REQUIRED>

=== Iamgovinda/BCA3rdSem/Webtechnology/XML/sarika.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shop SYSTEM "sarika.dtd">
<shop location="Satungal" size="Large" name="Sarika's shop">
    <food>
        <name>Pineapple</name>
        <type>fruit</type>
        <cost>600</cost>
    </food>
    <food>
        <name>cabbage</name>
        <type>vegetable</type>
 
        <boge>djsj</boge>
    </food>
</shop>
